### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Banyueqin** [wushilian/CRNN_Attention_OCR#1]
Traceback (most recent call last):
  File "/home/jxf/CRNN_Attention_OCR-master/train.py", line 24, in <module>
    img,label=cfg.read_data(cfg.train_dir)
  File "/home/jxf/CRNN_Attention_OCR-master/config.py", line 64, in read_data
    img = cv2.resize(im, (IMAGE_WIDTH,IMAGE_HEIGHT))
cv2.error: /io/opencv/modules/imgproc/src/imgwarp.cpp:3483: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by wushilian** [comment]
check your image,it seems like some of image are spoiled.

**Comment by Banyueqin** [comment]
thanks
