### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by olfaa** [wushilian/CRNN_Attention_OCR#16]
当我执行此代码时会显示错误消息，请有人可以帮助我
when I execute this code an error message is displayed, please someone can help me
![capture du 2018-04-23 13-38-10](https://user-images.githubusercontent.com/28719465/39127419-e550bee2-46fc-11e8-8d0d-fe6b2c3e3b8e.png)

**Comment by wushilian** [comment]
@olfaa 图片有问题

**Comment by olfaa** [comment]
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/resize.cpp, line 4044
Traceback (most recent call last):
  File "train.py", line 25, in <module>
    img,label=cfg.read_data(cfg.train_dir)
  File "/home/olfa/Bureau/Projet OCR/CRNN_Attention_OCR_Chinese-master/config.py", line 67, in read_data
    img = cv2.resize(im, (IMAGE_WIDTH,IMAGE_HEIGHT))
cv2.error: /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize

**Comment by yourlovedu** [comment]
@olfaa 这个是opencv读取图片返回None的问题，将读取图片的代码         
   im = cv2.imread(image_name, 0)  # /255.#read the gray image
替换为
            im = cv2.imdecode(np.fromfile(image_name,dtype=np.uint8),-1)
            im = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY) 
            if im is None:
                continue
就可以了

**Comment by MatrixPlayer** [comment]
im = cv2.imdecode(np.fromfile(image_name,dtype=np.uint8),0)  will be ok
