### ISSUE TITLE
an error 

### ISSUE THREAD

**Issue by SJHBXShub** [wushilian/CRNN_Attention_OCR#24]
Hi,  wu
I confront this error when I run train.py. Do you know how to solved this problem?

Traceback (most recent call last):
  File "train.py", line 50, in <module>
    **sess.run( train_op,feed_dict={image: batch_inputs,train_output: batch_target_in,target_output: batch_target_out,sample_rate:np.min([1.,0.2*cur_e
poch+0.2])})**
  File "/home/sjhbxs/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/sjhbxs/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/sjhbxs/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/sjhbxs/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
**tensorflow.python.framework.errors_impl.InvalidArgumentError:** The node 'gradients/decode/decoder/while/BasicDecoderStep/ScheduledEmbeddingTrainingHe
lperSample_1/cond/Gather_1_grad/ExpandDims/StackPush' has inputs from different frames. The input 'gradients/decode/decoder/while/BasicDecoderStep/S
cheduledEmbeddingTrainingHelperSample_1/cond/Gather_1_grad/Size' is in frame ''. The input 'gradients/decode/decoder/while/BasicDecoderStep/Schedule
dEmbeddingTrainingHelperSample_1/cond/Gather_1_grad/ExpandDims/StackPush/Switch' is in frame 'decode/decoder/while/decode/decoder/while/'.

**Comment by SJHBXShub** [comment]
Hi, wu
I have solved this problem by **deleting line 10 in train.py**(with tf.control_dependencies(update_ops):)
Hope this suggestion will help others

Brs

**Comment by wushilian** [comment]
@SJHBXShub Thank you,I will fix this error
